[build]
  # Directory with the serverless Lambda functions to deploy to AWS.
  functions = "functions"

[[redirects]]
  from = "/request-demo"
  to = "/.netlify/functions/request-demo/request-demo.js"
  method="POST"